# Generated by Django 3.2.9 on 2021-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('imdb', models.IntegerField(default=1)),
                ('genrer', models.CharField(choices=[('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime and mystery', 'Crime and mystery')], max_length=180)),
                ('actors', models.ManyToManyField(related_name='movie', to='music.Actor')),
            ],
        ),
    ]
